Swagger budget
gdsc-kaist/board-of-audit-and-inspection-system pull request #1
Opened 2023-09-25 16:00 UTC by yym0329

은재와 제가 Budget 부분 맡았습니다. 따로 Documentation 작업하기로 했고, 분담은 다음과 같이 했어요.

### 분담
@yym0329 : Expense 관련, `post: '/:organization_id/:year/:half’`, `'GET: budget/'`

진은재: Income 관련, ,`delete: '/:organization_id/:year/:half’`

---

### 작업 내용
`GET: /report/expense/:organization_id/:year/:half`

이 API, 쿼리문 해석이 좀 어려워서 남겨뒀고, 나머지는 Documentation 작성 했어요.

위 API는 일단 ChatGPT 활용해서 뭐하는 API인지 이해는 했는데, 어떤 방식으로 Swagger 문서를 작성해야할지 잘 모르겠습니다. 그래서 아래 노션 페이지에 swagger 문서 일부를 기록해 두고, 실제 swagger.yaml에는 남기지 않았습니다.

https://www.notion.so/kaist-students/Budget-4f623ad28fb34318bbd675d52f9f86bd?pvs=4

2023-09-30 12:32 UTC, Byunk commented
api 주소가 잘못 설정되어 있습니다
/budget -> /budgets
/expense -> /expenses 등등

2023-09-30 12:40 UTC, Byunk requested changes

2023-09-30 12:40 UTC, Byunk commented on swagger.yaml
> +        Expense:
example 추가해주세요

2023-09-30 12:40 UTC, Byunk commented on swagger.yaml
> +                    description: A unique identifier for each expense entry.
한글로 바꿔주세요!

2023-10-04 17:52 UTC, yym0329 commented on swagger.yaml
> +        Expense:
추가했습니다

2023-10-04 17:53 UTC, yym0329 commented
수정했어요 확인 부탁합니다~

2023-10-07 15:53 UTC, Byunk approved these changes

2023-10-07 15:56 UTC, closed without merging