Feat/access control
gdsc-kaist/board-of-audit-and-inspection-system pull request #8
Opened 2023-10-30 16:28 UTC by yym0329

API docs 수정했습니다.
API docs에 따라 Authorization middleware 넣었습니다.
로컬환경에서 role에 따라 엑세스 제한되는 것 확인했습니다.

Swagger docs의 GET:/budgets의 response code 200의 예시에 오류가 있어서, 수정이 필요합니다. Component Schema의 Budget을 예시 형식으로 reference하고 있습니다. Budget 스키마를 swagger docs에 추가하는 작업이 필요할 것 같습니다. 이거는 제가 다음 할일 하면서 할게요.

늦어서 죄송합니다

2023-10-30 16:35 UTC, yym0329 commented
users 관련 API에서 로그인과 비밀변경을 제외하고는 현재 모든 API가 어드민 유저만 사용 가능해야 한다고 생각합니다. (모든 유저 조회, 계정 생성, 유저 enable/disable)

그런데 그렇게 하면 npm run test단계에서 get:/users, 그리고 유저 disable api에서 이슈가 뜹니다. 아마도 test 코드에서 해당 API들을 어드민 권한으로 다루지 않는 등의 이슈가 있는 것 같아요.

2023-11-01 07:12 UTC, Byunk commented on src/middleware/validate.ts
> +            return res.status(403).json({ error: 'Not authorized as admin' });
`json` format보다 현재로서는 send를 이용해 에러 메시지를 보내는 방식을 택하고 있어서 포맷을 맞춰주면 좋을 것 같아요

2023-11-01 07:17 UTC, Byunk requested changes

2023-11-01 07:17 UTC, Byunk commented on .gitignore
> +.vscode/
.vscode 는 `vscode` IDE의 설정을 공유하기 위해 존재하는 폴더입니다. gitignore에 추가한 이유가 있을까요?
그리고 이렇게 이미 commit history에 존재하는 파일을 gitignore에 추가할 경우 문제가 발생합니다. 아마 `.vscode`가 제대로 ignore되지 않을 거에요. 우선 이부분은 다시 원래대로 복원하는 것이 좋아보입니다.

2023-11-01 07:17 UTC, Byunk commented on src/routes/user.ts
> +            role: req.body.role,
삭제 필요. 이는 의도적으로 API를 통해 admin 계정을 만들지 못하게 하기 위함입니다.

2023-11-01 07:21 UTC, Byunk commented
@yym0329  추가로 `validateIsLogin` 혹은 `validateIsUser` 등의 middleware를 추가하여, 유저가 로그인 되어 있는지 여부를 파악하는 middleware를 분리하는 것이 필요해보입니다.
현재는 `const role = req.session.user!.role;`를 통해 세션에 user가 없으면 에러가 발생하도록 되어 있더라구요.

2023-11-01 07:23 UTC, Byunk commented
@yym0329 그리고 말씀해주신 "users 관련 API에서 로그인과 비밀변경을 제외하고는 현재 모든 API가 어드민 유저만 사용 가능해야 한다"에 동의합니다. validation logic에 대한 테스트 코드 및 기존 테스트 케이스를 수정할테니 auto checking이 fail 되더라도 해당 부분 적용해서 commit 해주시겠어요?

2023-11-01 09:57 UTC, yym0329 commented on .gitignore
> +.vscode/
제 개인 vscode 설정이 올라갈까봐 해뒀던 건데 필요 없는거면 삭제하겠습니다!

2023-11-01 09:58 UTC, yym0329 commented on src/routes/user.ts
> +            role: req.body.role,
알겠습니다~ 근데 그러면 유저 가입할 때 role은 어디서 설정되나요?

2023-11-01 09:58 UTC, yym0329 commented
validateIsLogin 혹은 validateIsUser 등의 middleware 추가하고, 언급한 내용 반영해서 다시 커밋하겠습니다

2023-11-04 14:06 UTC, yym0329 commented
언급한 내용 반영해서 수정했습니다.

일단 user api 중 로그인과 비밀번호 변경 제외하고 모든 api에 admin validate하도록 미들웨어 추가해 놓았습니다.

2023-11-19 15:57 UTC, Byunk commented
@yym0329 merge 작업은 완료됐고, 기존 테스트 업데이트하면 될 것 같습니다. TODO로 작성해주신 admin일 경우 middleware skip하는 것은 merge하면서 구현했습니다.

2023-11-20 01:49 UTC, yym0329 commented
넵 감사합니다 ~ 기존 테스트 업데이트라는 것은 User API에서의 테스트케이스들 세분화 말하시는거죠?

2023-11-26 13:22 UTC, Byunk approved these changes

2023-11-26 13:22 UTC, merged